# Generated by Django 5.2.8 on 2025-12-02 01:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matric_number',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Matric number must follow the format PPE0000 (e.g., PPE1234).', regex='^PPE\\d{4}$')]),
        ),
    ]
