# Generated by Django 5.2.8 on 2025-11-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_examattempt_exam_alter_examattempt_attempt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='marks',
            field=models.FloatField(default=1),
        ),
    ]
